export const setPaciente = 'dashboard/setPaciente'
export const setGasometria = 'dashboard/setGasometria'
export const setSimetria = 'dashboard/setSimetria'
export const setVentilador = 'dashboard/setVentilador'
export const setCateter = 'dashboard/setCateter'
export const setProcedimentos = 'dashboard/setProcedimentos'
export const setProcedimentosConfig = 'dashboard/setProcedimentosConfig'
export const setTypeDashboard = 'dashboard/setTypeDashboard'
